/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { AppService } from './services/app.service';
export { FilesService } from './services/files.service';
export { GamesService } from './services/games.service';
