/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface FilesControllerUploadFile$Params {
      body: {

/**
 * File to upload
 */
'file'?: Blob;
}
}

export function filesControllerUploadFile(http: HttpClient, rootUrl: string, params: FilesControllerUploadFile$Params, context?: HttpContext): Observable<StrictHttpResponse<{

/**
 * Original filename
 */
'filename'?: string;

/**
 * File size in bytes
 */
'size'?: number;

/**
 * URL to access the uploaded file
 */
'url'?: string;
}>> {
  const rb = new RequestBuilder(rootUrl, filesControllerUploadFile.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      
      /**
       * Original filename
       */
      'filename'?: string;
      
      /**
       * File size in bytes
       */
      'size'?: number;
      
      /**
       * URL to access the uploaded file
       */
      'url'?: string;
      }>;
    })
  );
}

filesControllerUploadFile.PATH = '/files/upload';
