/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GameDto {
  id: string;
  key: string;
  modes: Array<'CLASSIC'>;
  name: string;
  photoUrl: string;
}
